management:
  health:
    kubernetes:
      enabled: false
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health
